INSERT INTO food_insights (
    food_id, short_label, theme, headline, subtitle, body, effects,
    warning_title, warning_body, education_title, education_body,
    highlight_title, highlight_points
)
VALUES
(
    8,
    'Refined Carb',
    'refined_carbs',
    'How this ingredient affects your energy',
    'What happens in your body',
    'White bread is made from very fine flour. Because it contains little fiber, your body can break it down quickly.',
    '["Faster energy release", "Shorter feeling of fullness"]'::jsonb,
    NULL,
    NULL,
    'What does “refined” mean?',
    'It means parts of the grain were removed during processing. Those parts usually contain fiber.',
    'Foods with more fiber',
    '["Are digested more slowly", "Support steadier energy"]'::jsonb
),
(
    7,
    'Fiber',
    'whole_grains',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Whole grain bread contains more fiber than white bread. Fiber slows digestion and helps energy last longer.',
    '["Slower energy release", "Longer feeling of fullness"]'::jsonb,
    NULL,
    NULL,
    'Why does fiber matter?',
    'Fiber helps slow how quickly carbohydrates are broken down and absorbed.',
    'Why whole grains can help',
    '["Support steadier blood sugar", "May help reduce cravings later"]'::jsonb
),
(
    148,
    'Refined Carb',
    'refined_carbs',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Croissants are rich in refined flour and fat. They can give quick energy at first, but may not keep blood sugar very stable.',
    '["Quick energy release", "May be less filling than expected"]'::jsonb,
    NULL,
    NULL,
    'Why can this happen?',
    'Refined carbohydrates are digested more quickly than whole-grain options.',
    'Try pairing with',
    '["Protein", "Fiber", "Healthy fats"]'::jsonb
),
(
    128,
    'Quick Carb',
    'quick_carbs',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Waffles are usually made from refined flour and can be digested quickly.',
    '["Quick energy release", "Possible earlier hunger"]'::jsonb,
    NULL,
    NULL,
    'Why?',
    'Meals based mostly on refined carbs may raise blood sugar faster.',
    'How to balance it',
    '["Add protein", "Add fiber", "Add healthy fats"]'::jsonb
),
(
    147,
    'Quick Carb',
    'quick_carbs',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Pancakes can provide quick energy, especially when eaten without protein or fiber-rich foods.',
    '["Quick energy release", "Possible shorter satiety"]'::jsonb,
    NULL,
    NULL,
    'Why?',
    'Refined carbohydrate-based meals are usually digested more quickly.',
    'How to balance it',
    '["Pair with yogurt", "Add nuts or seeds", "Choose fruit instead of syrup"]'::jsonb
),
(
    18,
    'Quick Sugar',
    'juice',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Orange juice contains natural sugars but little fiber compared with whole oranges, so sugar enters the bloodstream more quickly.',
    '["Quick sugar absorption", "Less filling than whole fruit"]'::jsonb,
    NULL,
    NULL,
    'Why is whole fruit different?',
    'Whole fruit contains fiber, which slows digestion and supports steadier blood sugar.',
    'Try instead',
    '["Whole oranges", "Berries", "Pair juice with protein"]'::jsonb
),
(
    17,
    'Quick Sugar',
    'juice',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Apple juice contains sugar without much fiber, so it can raise blood sugar faster than a whole apple.',
    '["Quick sugar absorption", "Less satiety than whole fruit"]'::jsonb,
    NULL,
    NULL,
    'Why is whole fruit different?',
    'Whole apples contain fiber, which slows digestion and helps fullness last longer.',
    'Try instead',
    '["Whole apples", "Nuts with fruit", "Yogurt and fruit"]'::jsonb
),
(
    129,
    'Protein',
    'protein',
    'Eat more Protein',
    'Suggestion',
    'Eggs provide protein that can help slow digestion and make breakfast more satisfying.',
    '["Can help you feel full longer", "May keep energy more stable", "Can support steadier blood sugar"]'::jsonb,
    NULL,
    NULL,
    'How protein helps your blood sugar',
    'Protein is digested more slowly than simple carbohydrates and can help flatten the blood sugar curve.',
    'Good breakfast role',
    '["Useful with bread", "Useful with fruit", "Useful with oats"]'::jsonb
),
(
    131,
    'Protein',
    'protein',
    'Eat more Protein',
    'Suggestion',
    'Egg omelet provides protein that can help slow digestion and support satiety.',
    '["Can help you feel full longer", "May keep energy more stable"]'::jsonb,
    NULL,
    NULL,
    'How protein helps',
    'Protein can reduce how quickly sugar enters the bloodstream when eaten with carbohydrates.',
    'Good breakfast role',
    '["Pairs well with bread", "Pairs well with vegetables"]'::jsonb
),
(
    137,
    'Protein',
    'protein',
    'Eat more Protein',
    'Suggestion',
    'Skyr is rich in protein and can help reduce energy drops later in the morning.',
    '["Can help you feel full longer", "May keep energy more stable", "Can help reduce cravings"]'::jsonb,
    NULL,
    NULL,
    'How protein helps your blood sugar',
    'Protein is digested more slowly than carbs. This helps flatten the blood sugar curve and can prevent the mid-morning energy crash.',
    'Good Protein Sources for Breakfast',
    '["Skyr", "Eggs", "Nuts", "Cheese", "Seeds"]'::jsonb
),
(
    146,
    'Protein',
    'protein',
    'Eat more Protein',
    'Suggestion',
    'Greek yogurt provides protein and can support satiety and steadier energy.',
    '["Can help you feel full longer", "May keep energy more stable"]'::jsonb,
    NULL,
    NULL,
    'How protein helps',
    'Protein slows digestion and can reduce the speed at which sugar enters the bloodstream.',
    'Good breakfast role',
    '["Pairs well with fruit", "Pairs well with granola in moderation"]'::jsonb
),
(
    134,
    'Protein',
    'protein',
    'Eat more Protein',
    'Suggestion',
    'Cottage cheese is a protein-rich option that can help make breakfast more filling.',
    '["Supports satiety", "May help reduce hunger later"]'::jsonb,
    NULL,
    NULL,
    'Why protein helps',
    'Protein can improve fullness and support more stable energy through the morning.',
    'Good breakfast role',
    '["Pairs well with bread", "Pairs well with vegetables"]'::jsonb
),
(
    141,
    'Protein',
    'protein',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Smoked salmon provides protein and fat, which can support satiety and steadier energy.',
    '["Longer-lasting fullness", "More stable energy release"]'::jsonb,
    NULL,
    NULL,
    'Why protein and fat help',
    'Protein and fat slow digestion compared with simple carbohydrates.',
    'Good breakfast role',
    '["Pairs well with bread", "Pairs well with eggs", "Pairs well with vegetables"]'::jsonb
),
(
    144,
    'Lean Protein',
    'protein',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Turkey slices are relatively lean and provide protein that can help support satiety.',
    '["More stable energy", "Can support fullness"]'::jsonb,
    NULL,
    NULL,
    'Why lean protein helps',
    'Lean protein can improve fullness without adding much sugar.',
    'Good breakfast role',
    '["Useful in sandwiches", "Useful with bread and vegetables"]'::jsonb
),
(
    143,
    'Fat & Protein',
    'processed_meat',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Salami is high in protein but also very high in fat. Because it contains almost no carbohydrates, your body does not get quick energy from it. Instead, it digests more slowly.',
    '["Slower, longer lasting energy release", "Longer feeling of fullness", "High calorie intake in small portions"]'::jsonb,
    'As processed meat, it should be eaten only in moderation',
    'Due to high fat and salt content, salami is best enjoyed in limited amounts.',
    'What does “high fat” mean?',
    'It means a large part of the calories comes from fat. Fat provides more than twice as much energy per gram as carbohydrates or protein.',
    'Things to keep in mind',
    '["Often high in salt", "Very calorie-dense", "Best in small portions"]'::jsonb
),
(
    139,
    'Fat & Protein',
    'processed_meat',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Bacon provides fat and some protein, but is also a processed meat and should be eaten in moderation.',
    '["Can slow digestion", "Very calorie-dense", "Not much quick energy"]'::jsonb,
    'Best in moderation',
    'Because bacon is processed and high in fat and salt, it is better as a small part of the meal.',
    'Why moderation matters',
    'Processed meats can be high in salt and saturated fat.',
    'Things to keep in mind',
    '["Small portions go a long way", "Balance with vegetables and protein"]'::jsonb
),
(
    156,
    'Healthy Fats',
    'healthy_fats',
    'Eat More Healthy Fats',
    'How Healthy Fats Help',
    'Healthy fats slow down how quickly sugar enters the bloodstream.',
    '["May keep energy more stable", "Can help you feel less tired"]'::jsonb,
    NULL,
    NULL,
    'Why?',
    'This can prevent rapid spikes and crashes in blood sugar levels, helping to keep your energy more stable throughout the morning.',
    NULL,
    '[]'::jsonb
),
(
    157,
    'Healthy Fats',
    'healthy_fats',
    'Eat More Healthy Fats',
    'How Healthy Fats Help',
    'Guacamole provides fats that can help slow digestion and make a meal more satisfying.',
    '["May support steadier energy", "Can improve satiety"]'::jsonb,
    NULL,
    NULL,
    'Why?',
    'Healthy fats can help reduce how quickly carbohydrates are absorbed.',
    NULL,
    '[]'::jsonb
),
(
    151,
    'Healthy Fats',
    'healthy_fats',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Peanut butter contains fat and some protein, which can help slow digestion and improve satiety.',
    '["More stable energy", "Can help you feel full longer"]'::jsonb,
    NULL,
    NULL,
    'Why it helps',
    'Fats and protein can make carbohydrate-based breakfasts more balanced.',
    'Good breakfast role',
    '["Useful with bread", "Useful with fruit"]'::jsonb
),
(
    152,
    'Healthy Fats',
    'healthy_fats',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Walnuts provide healthy fats and can help make breakfast more satisfying.',
    '["Support fullness", "May help slow digestion"]'::jsonb,
    NULL,
    NULL,
    'Why fats help',
    'Fats slow digestion compared with simple carbohydrates alone.',
    NULL,
    '[]'::jsonb
),
(
    153,
    'Healthy Fats',
    'healthy_fats',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Almonds provide healthy fats and can help make breakfast more balanced.',
    '["Support fullness", "May help steady energy"]'::jsonb,
    NULL,
    NULL,
    'Why fats help',
    'Healthy fats can help slow down how quickly sugar enters the bloodstream.',
    NULL,
    '[]'::jsonb
),
(
    155,
    'Fiber & Fats',
    'fiber_fats',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Chia seeds contain fiber and fats, which can support steadier digestion and fullness.',
    '["Can support satiety", "May help reduce spike risk"]'::jsonb,
    NULL,
    NULL,
    'Why fiber helps',
    'Fiber slows digestion and can help keep energy more stable.',
    NULL,
    '[]'::jsonb
),
(
    158,
    'Hydrating',
    'hydration',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Cucumber contains a lot of water and very few calories. It does not give much quick energy, but it can support hydration and freshness in a meal.',
    '["Supports hydration", "Adds volume with few calories"]'::jsonb,
    NULL,
    NULL,
    'Why hydration matters',
    'Staying hydrated can support concentration and how energized you feel during the morning.',
    NULL,
    '[]'::jsonb
),
(
    21,
    'Hydrating',
    'hydration',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Tomato adds water and volume to a meal with relatively little sugar and energy.',
    '["Supports hydration", "Adds freshness to a meal"]'::jsonb,
    NULL,
    NULL,
    'Why this can help',
    'Foods with a lot of water can make breakfast feel lighter and more balanced.',
    NULL,
    '[]'::jsonb
),
(
    179,
    'Flavonoids',
    'cocoa',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Unsweetened cocoa powder contains plant compounds called flavonoids. Depending on how it is used, it can add flavor with relatively little sugar.',
    '["Contains flavonoids", "Can be part of a more balanced breakfast"]'::jsonb,
    NULL,
    NULL,
    'What are flavonoids?',
    'Flavonoids are plant compounds found in cocoa that are often discussed for their antioxidant properties.',
    NULL,
    '[]'::jsonb
),
(
    178,
    'Sweet Drink',
    'sweet_drink',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Hot chocolate can provide quick energy when it contains sugar, but it may also raise blood sugar more quickly.',
    '["Quick energy", "Possible earlier dip later"]'::jsonb,
    NULL,
    NULL,
    'Why?',
    'Sugary drinks are usually absorbed faster than foods containing fiber or more protein.',
    NULL,
    '[]'::jsonb
);