INSERT INTO food_insights (
    food_id, short_label, theme, headline, subtitle, body, effects,
    warning_title, warning_body, education_title, education_body,
    highlight_title, highlight_points
)
VALUES
(
    1,
    'Slow Carbs',
    'whole_grains',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Multigrain oatmeal provides carbohydrates together with fiber, which can support a steadier rise in energy than more refined breakfast cereals.',
    '["Slower energy release", "Can support fullness", "May help reduce spike risk"]'::jsonb,
    NULL,
    NULL,
    'Why oats can help',
    'Oats usually contain more fiber than refined cereals, which helps slow digestion.',
    'Good breakfast role',
    '["Useful base for breakfast", "Pairs well with nuts, seeds, or yogurt"]'::jsonb
),
(
    2,
    'Fiber',
    'whole_grains',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Muesli usually combines grains, seeds, and sometimes dried fruit, which can make it more balanced than refined cereals depending on the ingredients.',
    '["Can provide fiber", "May be more filling than refined cereal"]'::jsonb,
    NULL,
    NULL,
    'What to watch for',
    'Some muesli mixes contain added sugar or a lot of dried fruit, which can increase sugar content.',
    'How to balance it',
    '["Pair with protein", "Check added sugar", "Add nuts or yogurt"]'::jsonb
),
(
    3,
    'Refined Cereal',
    'refined_carbs',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Special K is a more processed cereal and may provide energy quickly, especially if eaten without protein or fiber-rich foods.',
    '["Quick energy release", "Possible shorter satiety"]'::jsonb,
    NULL,
    NULL,
    'Why can this happen?',
    'More refined cereals are usually digested faster than whole-grain options.',
    'How to balance it',
    '["Add yogurt or milk", "Add berries", "Add nuts or seeds"]'::jsonb
),
(
    4,
    'Refined Cereal',
    'refined_carbs',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Cheerios can be part of breakfast, but on their own they may not keep you full for long unless paired with protein or healthy fats.',
    '["Moderate to quick energy release", "May need protein for better satiety"]'::jsonb,
    NULL,
    NULL,
    'Why balance matters',
    'A cereal-based breakfast is usually more satisfying when combined with protein and fiber.',
    'How to balance it',
    '["Add milk or yogurt", "Add fruit", "Add seeds"]'::jsonb
),
(
    5,
    'Quick Oats',
    'quick_carbs',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Instant oatmeal is usually more processed than traditional oats, so it can be digested a bit faster.',
    '["Faster energy release than traditional oats", "Still more balanced than many refined cereals"]'::jsonb,
    NULL,
    NULL,
    'Why processing matters',
    'The more a grain is processed, the faster it is often digested.',
    'How to balance it',
    '["Add nuts", "Add seeds", "Add yogurt or milk"]'::jsonb
),
(
    6,
    'Refined Cereal',
    'refined_carbs',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Cornflakes are made from refined grains and are usually digested quickly, especially when eaten without protein or fiber-rich foods.',
    '["Quick energy release", "Possible earlier hunger"]'::jsonb,
    NULL,
    NULL,
    'Why can this happen?',
    'Refined cereals contain less fiber than whole-grain options.',
    'How to balance it',
    '["Add protein", "Add nuts or seeds", "Choose whole-grain alternatives"]'::jsonb
),
(
    9,
    'Refined Carb',
    'refined_carbs',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Baguette is usually made from refined flour and can provide quick energy, but often with less fiber than whole-grain bread.',
    '["Quick energy release", "Less lasting fullness"]'::jsonb,
    NULL,
    NULL,
    'Why whole grain is different',
    'Whole-grain breads usually contain more fiber, which supports slower digestion.',
    'Try pairing with',
    '["Protein", "Healthy fats", "Vegetables"]'::jsonb
),
(
    10,
    'Protein + Carb',
    'dairy',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Whole milk provides some protein, fat, and lactose, which can make breakfast a bit more balanced than carbs alone.',
    '["Can support satiety", "More balanced than sugary drinks"]'::jsonb,
    NULL,
    NULL,
    'What is lactose?',
    'Lactose is the natural sugar found in milk.',
    'Good breakfast role',
    '["Useful with cereal or oats", "Adds protein and fat"]'::jsonb
),
(
    11,
    'Protein + Carb',
    'dairy',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Skim milk provides protein and lactose, but less fat than whole milk.',
    '["Adds protein", "Less fat, so a bit less satiety than whole milk"]'::jsonb,
    NULL,
    NULL,
    'Why fat changes satiety',
    'Fat can slow digestion and help a meal feel more filling.',
    'Good breakfast role',
    '["Useful with cereal", "Useful with oats"]'::jsonb
),
(
    12,
    'Sweet Dairy',
    'sweet_dairy',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Sweetened Greek yogurt can still provide protein, but added sugar may raise blood sugar faster than plain versions.',
    '["Protein support", "Added sugar may increase spike risk"]'::jsonb,
    NULL,
    NULL,
    'Why plain yogurt is different',
    'Plain yogurt has less sugar and can be easier to balance with fruit or nuts.',
    'Try instead',
    '["Plain Greek yogurt", "Skyr", "Add your own fruit"]'::jsonb
),
(
    13,
    'Protein',
    'protein',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Low-fat Greek yogurt provides protein, which can help support satiety and steadier energy.',
    '["Can help you feel full longer", "Supports more stable energy"]'::jsonb,
    NULL,
    NULL,
    'Why protein helps',
    'Protein slows digestion and can reduce how quickly sugar enters the bloodstream.',
    'Good breakfast role',
    '["Pairs well with berries", "Pairs well with oats"]'::jsonb
),
(
    14,
    'Sweet Drink',
    'sweet_drink',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Chocolate milk provides some protein from milk, but also more sugar than plain milk.',
    '["Quick energy", "Some protein support", "Can raise blood sugar faster than plain milk"]'::jsonb,
    NULL,
    NULL,
    'Why added sugar matters',
    'Added sugars can make energy rise faster, especially in liquid form.',
    'Try instead',
    '["Plain milk", "Milk with cocoa and less sugar"]'::jsonb
),
(
    15,
    'Plant Protein',
    'plant_protein',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Soy milk provides some protein and can be a useful plant-based option for a more balanced breakfast.',
    '["Adds protein", "Can support satiety better than many plant drinks"]'::jsonb,
    NULL,
    NULL,
    'Why soy is different',
    'Compared with some other plant milks, soy milk usually contains more protein.',
    'Good breakfast role',
    '["Useful with cereal", "Useful with oats", "Plant-based option"]'::jsonb
),
(
    16,
    'Savory Juice',
    'juice',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Tomato juice contains less sugar than many fruit juices, but still has less fiber than whole tomatoes.',
    '["Can be lighter in sugar than fruit juice", "Less fiber than whole vegetables"]'::jsonb,
    NULL,
    NULL,
    'Why whole vegetables are different',
    'Whole vegetables contain more fiber and often support better fullness.',
    'Try pairing with',
    '["Protein", "Eggs", "Cheese"]'::jsonb
),
(
    19,
    'Healthy Fats',
    'healthy_fats',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Peanuts provide fat and some protein, which can help make breakfast more filling.',
    '["Supports fullness", "May help slow digestion"]'::jsonb,
    NULL,
    NULL,
    'Why this helps',
    'Fat and protein can reduce how quickly carbs are absorbed.',
    NULL,
    '[]'::jsonb
),
(
    20,
    'Healthy Fats',
    'healthy_fats',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Cashews provide fat and some protein, which can support satiety as part of breakfast.',
    '["Supports fullness", "May help balance carb-based meals"]'::jsonb,
    NULL,
    NULL,
    'Why nuts can help',
    'Nuts add fat and some protein, which can make breakfast more satisfying.',
    NULL,
    '[]'::jsonb
),
(
    22,
    'Fiber',
    'vegetables',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Carrots add fiber and volume to a meal and can help make breakfast feel more balanced.',
    '["Adds fiber", "Adds crunch and volume"]'::jsonb,
    NULL,
    NULL,
    'Why vegetables help',
    'Vegetables add fiber and usually have a lower glycemic impact than refined breakfast foods.',
    NULL,
    '[]'::jsonb
),
(
    23,
    'Fruit',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Cherries provide natural sugars together with some fiber, which can make them more balanced than juice or sweets.',
    '["Natural sweetness", "More balanced than sugary drinks"]'::jsonb,
    NULL,
    NULL,
    'Why whole fruit helps',
    'Whole fruit contains fiber, which slows digestion compared with juice.',
    NULL,
    '[]'::jsonb
),
(
    106,
    'Citrus Fruit',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Grapefruit provides natural sugars together with water and some fiber, making it more balanced than juice.',
    '["Natural sweetness", "Contains some fiber", "Hydrating"]'::jsonb,
    NULL,
    NULL,
    'Why whole fruit helps',
    'Whole fruit is usually digested more slowly than fruit juice.',
    NULL,
    '[]'::jsonb
),
(
    107,
    'Berry',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Raspberries are naturally sweet but also provide fiber, which helps slow digestion.',
    '["More fiber than many fruits", "Can support steadier energy"]'::jsonb,
    NULL,
    NULL,
    'Why berries are often useful',
    'Berries often provide flavor and fiber with less sugar than many sweet breakfast add-ons.',
    NULL,
    '[]'::jsonb
),
(
    108,
    'Fruit',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Apples provide natural sugar together with fiber, which makes them more balanced than apple juice.',
    '["Natural sweetness", "Fiber helps slow digestion"]'::jsonb,
    NULL,
    NULL,
    'Why apple juice is different',
    'Juice removes much of the fiber and makes sugar easier to absorb quickly.',
    NULL,
    '[]'::jsonb
),
(
    109,
    'Fruit',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Pears provide natural sugar together with fiber and water, which can support steadier energy.',
    '["Contains fiber", "Can support satiety better than juice"]'::jsonb,
    NULL,
    NULL,
    'Why whole fruit helps',
    'Whole fruit is usually more filling than sweet drinks or syrups.',
    NULL,
    '[]'::jsonb
),
(
    110,
    'Berry',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Blueberries add sweetness and antioxidants, and can work well in a balanced breakfast.',
    '["Natural sweetness", "Can pair well with protein foods"]'::jsonb,
    NULL,
    NULL,
    'Why berries are useful',
    'Berries can add flavor without acting like a sweet spread or sugary drink.',
    NULL,
    '[]'::jsonb
),
(
    111,
    'Berry',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Strawberries add sweetness and freshness with relatively little sugar compared with many sweet toppings.',
    '["Natural sweetness", "Can help balance breakfast flavor"]'::jsonb,
    NULL,
    NULL,
    'Why berries are useful',
    'Berries can replace more sugary breakfast toppings in some meals.',
    NULL,
    '[]'::jsonb
),
(
    112,
    'Dried Fruit',
    'dried_fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Dates are naturally sweet but concentrated, so they can add a lot of sugar in a small portion.',
    '["Very sweet in small amounts", "Can raise sugar quickly if used in larger portions"]'::jsonb,
    NULL,
    NULL,
    'Why portion size matters',
    'Dried fruit is more concentrated than fresh fruit because much of the water is removed.',
    'Best use',
    '["Small amounts", "Pair with nuts or yogurt"]'::jsonb
),
(
    113,
    'Fruit',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Peaches provide natural sugar and water and can be a lighter fruit option at breakfast.',
    '["Natural sweetness", "Hydrating"]'::jsonb,
    NULL,
    NULL,
    'Why whole fruit helps',
    'Whole fruit is usually more balanced than fruit juice because it contains fiber.',
    NULL,
    '[]'::jsonb
),
(
    114,
    'Citrus Fruit',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Oranges provide natural sugar with fiber, so they are more balanced than orange juice.',
    '["Natural sweetness", "More fiber than juice"]'::jsonb,
    NULL,
    NULL,
    'Why whole fruit is different',
    'The fiber in whole fruit slows digestion compared with juice.',
    NULL,
    '[]'::jsonb
),
(
    115,
    'Fruit',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Green grapes provide quick natural sweetness but usually less fiber than berries.',
    '["Natural sweetness", "Can be easy to overeat"]'::jsonb,
    NULL,
    NULL,
    'Why portion size matters',
    'Some fruits are easy to eat quickly, so portion size can affect sugar intake.',
    NULL,
    '[]'::jsonb
),
(
    116,
    'Fruit',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Red grapes provide natural sweetness but relatively little fiber per bite compared with some other fruits.',
    '["Natural sweetness", "Can add quick sugar"]'::jsonb,
    NULL,
    NULL,
    'How to balance fruit',
    'Fruit often works well when paired with protein or healthy fats.',
    NULL,
    '[]'::jsonb
),
(
    117,
    'Fruit',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Kiwi provides natural sweetness with fiber and can be a balanced fruit choice for breakfast.',
    '["Natural sweetness", "Contains fiber"]'::jsonb,
    NULL,
    NULL,
    'Why whole fruit helps',
    'Whole fruit supports slower digestion than juice or sugary spreads.',
    NULL,
    '[]'::jsonb
),
(
    118,
    'Fruit',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Bananas provide quick energy and can be useful before activity, but pairing them with protein or fat may improve satiety.',
    '["Quick energy", "Better balanced with protein or fats"]'::jsonb,
    NULL,
    NULL,
    'How to balance bananas',
    'Bananas often work well with yogurt, nuts, or peanut butter.',
    NULL,
    '[]'::jsonb
),
(
    119,
    'Fruit',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Pineapple provides natural sweetness and can raise blood sugar more quickly than fruits with more fiber.',
    '["Natural sweetness", "Can act faster than higher-fiber fruits"]'::jsonb,
    NULL,
    NULL,
    'How to balance it',
    'Pairing fruit with protein or yogurt may improve fullness.',
    NULL,
    '[]'::jsonb
),
(
    120,
    'Dried Fruit',
    'dried_fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Raisins are concentrated fruit sugar, so they can add sweetness quickly in a small portion.',
    '["Concentrated sugar", "Small amounts go a long way"]'::jsonb,
    NULL,
    NULL,
    'Why dried fruit feels different',
    'Removing water makes dried fruit smaller and more concentrated.',
    'Best use',
    '["Use small portions", "Pair with nuts or yogurt"]'::jsonb
),
(
    121,
    'Hydrating Fruit',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Watermelon is very hydrating and refreshing, but it contains less fiber than some other fruits.',
    '["Hydrating", "Light and refreshing"]'::jsonb,
    NULL,
    NULL,
    'Why some fruits feel different',
    'Fruits vary in fiber, water, and sugar, so their impact on fullness can differ.',
    NULL,
    '[]'::jsonb
),
(
    122,
    'Sweet Spread',
    'sweet_spread',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Nutella combines sugar and fat. It may taste satisfying, but it can still add a lot of sugar quickly.',
    '["Sweet and calorie-dense", "Less protein than nut butter"]'::jsonb,
    NULL,
    NULL,
    'Why peanut butter is different',
    'Peanut butter usually provides more protein and less sugar than chocolate spread.',
    'Try instead',
    '["Peanut butter", "Nuts with fruit"]'::jsonb
),
(
    123,
    'Sweetener',
    'sweetener',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Stevia is used as a low-calorie sweetener and does not add the same sugar load as table sugar.',
    '["Very low sugar impact", "Used mainly for sweetness"]'::jsonb,
    NULL,
    NULL,
    'Why some people use it',
    'It can sweeten drinks or foods without adding much energy.',
    NULL,
    '[]'::jsonb
),
(
    124,
    'Sweetener',
    'sweetener',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Agave syrup is a sweetener and can still contribute a lot of sugar even if it is marketed as a natural option.',
    '["Adds concentrated sugar", "Easy to overuse"]'::jsonb,
    NULL,
    NULL,
    'Why “natural” does not always mean low impact',
    'Natural sweeteners can still contribute a lot of sugar and energy.',
    'Best use',
    '["Use small amounts", "Balance with protein and fiber"]'::jsonb
),
(
    125,
    'Sweetener',
    'sweetener',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Maple syrup is a concentrated sweetener and can raise blood sugar quickly if used generously.',
    '["Adds quick sugar", "Often used on refined carb breakfasts"]'::jsonb,
    NULL,
    NULL,
    'Why syrup matters',
    'Sweet toppings can increase the glycemic load of waffles, pancakes, or toast.',
    'Best use',
    '["Use small amounts", "Balance with protein or nuts"]'::jsonb
),
(
    126,
    'Sweet Topping',
    'sweet_spread',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Caramel is a concentrated sweet topping and can increase sugar load quickly.',
    '["Adds quick sugar", "Low satiety on its own"]'::jsonb,
    NULL,
    NULL,
    'Why toppings matter',
    'Sweet toppings can turn a moderate breakfast into a more spike-prone one.',
    'Try instead',
    '["Fruit", "Nuts", "Yogurt"]'::jsonb
),
(
    127,
    'Sweetener',
    'sweetener',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Honey is a natural sweetener, but it still contributes a lot of sugar.',
    '["Adds quick sugar", "Can raise glycemic load"]'::jsonb,
    NULL,
    NULL,
    'Natural does not always mean low impact',
    'Honey can still raise blood sugar, especially when added to refined carb meals.',
    'Best use',
    '["Use small amounts", "Pair with fiber or protein"]'::jsonb
),
(
    130,
    'Protein + Fat',
    'protein',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Eggs Benedict provides protein and fat, which can support satiety, but the meal can still be heavier depending on the bread and sauce.',
    '["Can be filling", "Contains both protein and fat"]'::jsonb,
    NULL,
    NULL,
    'Why overall composition matters',
    'A breakfast can include good protein and still be heavy if paired with refined carbs and rich sauces.',
    NULL,
    '[]'::jsonb
),
(
    132,
    'Fat & Protein',
    'cheese',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Hard cheese provides protein and fat, which can support satiety and slow digestion.',
    '["Supports fullness", "Very energy-dense in small amounts"]'::jsonb,
    NULL,
    NULL,
    'Why cheese can be useful',
    'Cheese can help balance bread-based breakfasts by adding protein and fat.',
    NULL,
    '[]'::jsonb
),
(
    133,
    'Protein',
    'protein',
    'How this ingredient affects your energy',
    'What happens in your body',
    'High-protein cheese provides a strong protein base and can help make breakfast more filling.',
    '["High protein", "Supports satiety"]'::jsonb,
    NULL,
    NULL,
    'Why protein matters',
    'Protein can reduce how quickly sugar enters the bloodstream when eaten with carbs.',
    NULL,
    '[]'::jsonb
),
(
    135,
    'Fat & Protein',
    'cheese',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Feta provides fat and protein, which can help balance a meal, though it is also relatively salty.',
    '["Supports satiety", "Adds flavor in small amounts"]'::jsonb,
    'Use in moderation',
    'Feta can be useful in breakfast, but it is also relatively high in salt.',
    'Why small amounts can work',
    'A little cheese can add satiety without needing a large portion.',
    NULL,
    '[]'::jsonb
),
(
    136,
    'Fat',
    'cheese',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Cream cheese adds fat and can make bread-based breakfasts feel more satisfying, but it is not very high in protein.',
    '["Adds fat", "Not much protein"]'::jsonb,
    NULL,
    NULL,
    'Why protein still matters',
    'Fat can help, but protein usually adds even more satiety support.',
    'How to improve it',
    '["Pair with protein", "Add vegetables"]'::jsonb
),
(
    138,
    'Plant Protein',
    'plant_protein',
    'Eat more Protein',
    'Suggestion',
    'Tofu provides plant-based protein and can support steadier energy and fullness.',
    '["Plant protein source", "Can support satiety", "Useful for vegan breakfasts"]'::jsonb,
    NULL,
    NULL,
    'Why protein helps',
    'Protein slows digestion and may reduce blood sugar swings after breakfast.',
    'Good breakfast role',
    '["Useful in savory breakfasts", "Pairs well with vegetables"]'::jsonb
),
(
    140,
    'Fat & Protein',
    'processed_meat',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Sausage provides protein and fat, but it is also a processed meat and can be high in salt and saturated fat.',
    '["Can be filling", "Processed meat", "Very energy-dense"]'::jsonb,
    'Best in moderation',
    'Sausage can add satiety, but it is usually better in smaller amounts.',
    'Why moderation matters',
    'Processed meats are often high in salt and fat.',
    NULL,
    '[]'::jsonb
),
(
    142,
    'Protein',
    'processed_meat',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Ham slices provide protein and can help make breakfast more filling, though processed versions are also higher in salt.',
    '["Adds protein", "Can support satiety"]'::jsonb,
    'Best in moderation',
    'Pre-packaged deli meats are often high in salt.',
    'Why moderation matters',
    'Protein is useful, but processed meats are still better as one part of the meal.',
    NULL,
    '[]'::jsonb
),
(
    145,
    'Fat',
    'healthy_fats',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Coconut oil adds fat but no meaningful protein or fiber, so it can help slow digestion but does not improve the meal in the same way as whole foods.',
    '["Adds fat", "Does not add protein or fiber"]'::jsonb,
    NULL,
    NULL,
    'Why whole foods are often better',
    'Foods like nuts, avocado, or seeds provide fats together with other helpful nutrients.',
    NULL,
    '[]'::jsonb
),
(
    149,
    'Crunchy Carbs',
    'mixed_cereal',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Granola can contain grains, fats, and sometimes nuts, but it may also be high in sugar depending on the recipe.',
    '["Can be filling", "May be higher in sugar than it looks"]'::jsonb,
    NULL,
    NULL,
    'What to watch for',
    'Granola often feels healthy, but some versions contain a lot of sugar or syrup.',
    'How to balance it',
    '["Use moderate portions", "Pair with yogurt", "Add berries instead of syrup"]'::jsonb
),
(
    150,
    'Fat',
    'fats',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Butter adds fat and can slow digestion a little, but it does not provide fiber or much protein.',
    '["Adds fat", "Does not add much satiety on its own"]'::jsonb,
    NULL,
    NULL,
    'Why whole-food fats are often more useful',
    'Foods like nuts, seeds, or avocado add fats together with fiber or protein.',
    NULL,
    '[]'::jsonb
),
(
    154,
    'Healthy Fats',
    'healthy_fats',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Olive oil adds healthy fats and can help slow digestion when eaten with carbohydrates.',
    '["Healthy fats", "May help reduce spike risk when paired with carbs"]'::jsonb,
    NULL,
    NULL,
    'Why fats help',
    'Fats can slow how quickly sugar enters the bloodstream.',
    NULL,
    '[]'::jsonb
),
(
    159,
    'Vegetable',
    'vegetables',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Green bell pepper adds volume, freshness, and a little fiber with very little sugar.',
    '["Adds volume", "Low glycemic impact"]'::jsonb,
    NULL,
    NULL,
    'Why vegetables help',
    'Vegetables can make breakfast more balanced without adding much sugar.',
    NULL,
    '[]'::jsonb
),
(
    160,
    'Vegetable',
    'vegetables',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Orange bell pepper adds color, crunch, and a little fiber with low glycemic impact.',
    '["Adds volume", "Low glycemic impact"]'::jsonb,
    NULL,
    NULL,
    'Why vegetables help',
    'Vegetables can support balance in savory breakfasts.',
    NULL,
    '[]'::jsonb
),
(
    161,
    'Vegetable',
    'vegetables',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Red bell pepper adds flavor and a little fiber with relatively little sugar.',
    '["Adds flavor", "Low glycemic impact"]'::jsonb,
    NULL,
    NULL,
    'Why vegetables help',
    'Vegetables can improve fiber and volume without making breakfast much sweeter.',
    NULL,
    '[]'::jsonb
),
(
    162,
    'Vegetable',
    'vegetables',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Yellow bell pepper adds crunch and color with low glycemic impact.',
    '["Adds crunch", "Low glycemic impact"]'::jsonb,
    NULL,
    NULL,
    'Why vegetables help',
    'Vegetables can help make breakfast more balanced and satisfying.',
    NULL,
    '[]'::jsonb
),
(
    163,
    'Citrus',
    'fruit',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Lemon adds flavor with very little sugar and is usually not a main energy source in breakfast.',
    '["Adds flavor", "Low sugar in normal portions"]'::jsonb,
    NULL,
    NULL,
    'What lemon mainly does',
    'Lemon is usually used for flavor rather than energy or fullness.',
    NULL,
    '[]'::jsonb
),
(
    164,
    'Sweet Spread',
    'sweet_spread',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Jam adds sweetness quickly and usually does not add much protein or satiety.',
    '["Adds quick sugar", "Low satiety on its own"]'::jsonb,
    NULL,
    NULL,
    'Why this matters on bread',
    'Bread with jam can be a very carb-focused breakfast unless paired with protein or fats.',
    'Try instead',
    '["Peanut butter", "Cottage cheese", "Whole fruit"]'::jsonb
),
(
    165,
    'Mixed Meal',
    'mixed_meal',
    'How this ingredient affects your energy',
    'What happens in your body',
    'A breakfast burrito can be more balanced than sweet breakfasts if it includes protein, fats, and fiber, though this depends on the ingredients.',
    '["Can be balanced", "Depends heavily on filling and tortilla"]'::jsonb,
    NULL,
    NULL,
    'Why mixed meals vary',
    'Meals made of several ingredients can be either balanced or spike-prone depending on their composition.',
    NULL,
    '[]'::jsonb
),
(
    166,
    'Plant Drink',
    'plant_drink',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Oat milk often contains more carbohydrates than some other plant milks, so it may contribute more to glycemic load.',
    '["Can add carbs", "Usually less protein than dairy or soy milk"]'::jsonb,
    NULL,
    NULL,
    'Why plant milks differ',
    'Different plant milks vary a lot in protein, sugar, and fat.',
    'Try comparing with',
    '["Soy milk", "Unsweetened almond milk"]'::jsonb
),
(
    167,
    'Plant Drink',
    'plant_drink',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Unsweetened almond milk is usually low in sugar, but it also contains little protein.',
    '["Low sugar", "Low protein"]'::jsonb,
    NULL,
    NULL,
    'Why this matters',
    'A low-sugar drink is helpful, but protein still matters for fullness.',
    NULL,
    '[]'::jsonb
),
(
    168,
    'Coffee',
    'coffee',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Black brewed coffee contains almost no calories and does not meaningfully raise blood sugar on its own.',
    '["Very low sugar impact", "Often used for alertness rather than fullness"]'::jsonb,
    NULL,
    NULL,
    'What coffee changes most',
    'Coffee affects alertness more than it affects satiety or blood sugar.',
    NULL,
    '[]'::jsonb
),
(
    169,
    'Coffee',
    'coffee',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Espresso contains very little sugar and has almost no glycemic impact on its own.',
    '["Very low sugar impact", "Mainly affects alertness"]'::jsonb,
    NULL,
    NULL,
    'What matters more here',
    'The main breakfast impact usually comes from what is added to the coffee.',
    NULL,
    '[]'::jsonb
),
(
    170,
    'Coffee + Milk',
    'coffee',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Latte adds milk carbohydrates and can contribute a little more energy and sugar than black coffee.',
    '["More energy than black coffee", "Some milk sugar"]'::jsonb,
    NULL,
    NULL,
    'Why it differs from black coffee',
    'Milk adds lactose and some protein, so the drink becomes more nutritionally active.',
    NULL,
    '[]'::jsonb
),
(
    171,
    'Coffee + Milk',
    'coffee',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Cappuccino adds milk and a little sugar from lactose, but usually in smaller volume than a latte.',
    '["Some milk sugar", "Low to moderate breakfast impact"]'::jsonb,
    NULL,
    NULL,
    'What changes it most',
    'The size of the drink and any added sugar matter more than coffee itself.',
    NULL,
    '[]'::jsonb
),
(
    172,
    'Coffee',
    'coffee',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Turkish coffee itself has very little glycemic impact unless sugar is added.',
    '["Low glycemic impact by itself", "Mainly affects alertness"]'::jsonb,
    NULL,
    NULL,
    'What matters more',
    'Added sugar changes the impact much more than the coffee itself.',
    NULL,
    '[]'::jsonb
),
(
    173,
    'Sweetener',
    'sweetener',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Table sugar is absorbed quickly and can raise blood sugar rapidly, especially in drinks or on refined carbs.',
    '["Very quick sugar", "Can strongly increase glycemic load"]'::jsonb,
    NULL,
    NULL,
    'Why sugar in drinks matters',
    'Sugar in drinks is often absorbed especially quickly because there is little fiber to slow it down.',
    'Try instead',
    '["Use less", "Try stevia", "Pair with protein or fiber"]'::jsonb
),
(
    174,
    'Tea',
    'tea',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Herbal tea has almost no calories and does not meaningfully affect blood sugar on its own.',
    '["Very low sugar impact", "Mainly for hydration"]'::jsonb,
    NULL,
    NULL,
    'What it adds most',
    'Tea mainly adds warmth and hydration rather than energy or fullness.',
    NULL,
    '[]'::jsonb
),
(
    175,
    'Tea',
    'tea',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Black tea has almost no calories on its own and does not meaningfully raise blood sugar.',
    '["Very low sugar impact", "Mainly for hydration and alertness"]'::jsonb,
    NULL,
    NULL,
    'What matters more',
    'Added milk or sugar changes the impact more than the tea itself.',
    NULL,
    '[]'::jsonb
),
(
    176,
    'Tea',
    'tea',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Green tea has almost no glycemic impact on its own and is usually not a meaningful source of breakfast energy.',
    '["Very low sugar impact", "Mainly for hydration"]'::jsonb,
    NULL,
    NULL,
    'What matters more',
    'The additions, such as milk or sugar, matter more than the tea itself.',
    NULL,
    '[]'::jsonb
),
(
    177,
    'Tea + Milk',
    'tea',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Tea with milk adds some milk sugar and energy, but it is usually still a small part of the breakfast total.',
    '["Some milk sugar", "Low to moderate breakfast impact"]'::jsonb,
    NULL,
    NULL,
    'Why this differs from plain tea',
    'Milk adds lactose and some protein, making the drink more nutritionally active.',
    NULL,
    '[]'::jsonb
),
(
    180,
    'Sweet Drink',
    'sweet_drink',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Cocoa with milk can provide some protein from milk, but it may also contain enough sugar to raise blood sugar faster.',
    '["Sweet drink", "Some protein from milk", "Can contribute to spike risk"]'::jsonb,
    NULL,
    NULL,
    'Why this differs from cocoa powder',
    'Prepared cocoa drinks often contain more sugar than plain cocoa powder.',
    NULL,
    '[]'::jsonb
),
(
    181,
    'Fiber',
    'vegetables',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Broccoli adds fiber and volume with low glycemic impact, which can help make savory breakfasts more balanced.',
    '["Adds fiber", "Low glycemic impact", "Supports balance"]'::jsonb,
    NULL,
    NULL,
    'Why vegetables help',
    'Vegetables add bulk and fiber without much sugar.',
    NULL,
    '[]'::jsonb
),
(
    182,
    'Lean Protein',
    'protein',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Chicken provides protein, which can support satiety and make breakfast more filling.',
    '["Protein support", "Can help you feel full longer"]'::jsonb,
    NULL,
    NULL,
    'Why protein helps',
    'Protein is digested more slowly than simple carbohydrates and can reduce energy crashes.',
    NULL,
    '[]'::jsonb
),
(
    183,
    'Protein',
    'protein',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Fish provides protein and fats, which can help support satiety and steadier energy.',
    '["Protein support", "Can improve fullness", "Low sugar impact"]'::jsonb,
    NULL,
    NULL,
    'Why this can help',
    'Protein-rich foods often improve breakfast balance when paired with carbs.',
    NULL,
    '[]'::jsonb
),
(
    184,
    'Leafy Vegetable',
    'vegetables',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Lettuce adds volume and freshness with very little sugar or glycemic impact.',
    '["Adds volume", "Very low glycemic impact"]'::jsonb,
    NULL,
    NULL,
    'Why volume matters',
    'Low-calorie vegetables can help make meals feel more complete.',
    NULL,
    '[]'::jsonb
),
(
    185,
    'Vegetable',
    'vegetables',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Onions add flavor and some natural sugars, but in breakfast portions they are usually a moderate contributor.',
    '["Adds flavor", "Moderate impact in normal portions"]'::jsonb,
    NULL,
    NULL,
    'Why portions matter',
    'Ingredients used in smaller amounts usually affect the meal less than the main components.',
    NULL,
    '[]'::jsonb
),
(
    186,
    'Starchy Carb',
    'starchy_carbs',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Potatoes provide starchy carbohydrates and can raise blood sugar more quickly depending on preparation and portion size.',
    '["Can provide quick energy", "Preparation affects impact"]'::jsonb,
    NULL,
    NULL,
    'Why preparation matters',
    'Cooking and texture can change how quickly potato starch is digested.',
    'How to balance it',
    '["Pair with protein", "Add vegetables", "Add healthy fats"]'::jsonb
),
(
    187,
    'Leafy Vegetable',
    'vegetables',
    'How this ingredient affects your energy',
    'What happens in your body',
    'Spinach adds fiber, volume, and micronutrients with very little sugar or glycemic impact.',
    '["Very low glycemic impact", "Adds volume and balance"]'::jsonb,
    NULL,
    NULL,
    'Why leafy greens help',
    'Leafy vegetables can make savory breakfasts more balanced without adding much sugar.',
    NULL,
    '[]'::jsonb
)
ON CONFLICT (food_id) DO NOTHING;